### ISSUE TITLE
Unresolved dependencies in using dl4j-spark-ml

### ISSUE THREAD

**Issue by Lewuathe** [deeplearning4j/dl4j-spark-ml#7]
When I run `sbt console` under dl4j-spark-ml project, [this](https://gist.github.com/Lewuathe/4ed9b1a06620844921a5) error has been occurred. As written in README.md, I deleted `~/ivy2/cache/org.deeplearning4j`. But this is not successful.

> Delete ~/.ivy2/cache/org.deeplearning4j and similar as necessary.

In order to resolve this problem, we have to delete all ivy cache. Or is there any good workaround here?
Deleting cache and downloading all dependencies again take always a lot of time.

**Comment by lantianyouyou** [comment]
I have the same problem as Lewuathe's.  there are a lot of "unresolved dependency..." errors.
e.g., 
unresolved dependency: org.apache.commons#commons-compress;1.8.1: 
unresolved dependency: org.apache.commons#commons-io;1.3.2:
unresolved dependency: com.fasterxml.jackson.core#jackson-core;2.5.1:
unresolved dependency: net.bytebuddy#byte-buddy;0.6.14:
unresolved dependency: org.hamcrest#hamcrest-core;1.3:
unresolved dependency: org.springframework#spring-core;3.2.5.
unresolved dependency: org.reflections#reflections;0.9.10
unresolved dependency: io.netty#netty-buffer;4.0.28
unresolved dependency: org.projectlombok#lombok;1.16.4
unresolved dependency: com.twelvemonkeys.imageio#imageio-tiff;3.1.1:
unresolved dependency: com.twelvemonkeys.imageio#imageio-psd;3.1.1:
unresolved dependency: org.slf4j#slf4j-api;1.7.12
unresolved dependency: io.netty#netty-buffer;4.0.28
unresolved dependency: org.projectlombok#lombok;1.16.4:
unresolved dependency: ch.qos.logback#logback-classic;1.1.2
.......
question is: is there any 3rd-party libs that dl4j-spark-ml requires?

**Comment by agibsonccc** [comment]
Lots unfortunately. We usually just wipe the cache atm. Please come on gitter in the spark-ml channel. We are happy to answer questions:

https://gitter.im/deeplearning4j/dl4j-spark-ml
